title: Lords of the Pit
email: 
description: Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.
baseurl: /
url: https://lordsofthepit.com
googleAnalytics: 
permalink: pretty
sort_by: year, month
markdown: kramdown
plugins:
  - jekyll-feed
include: ['_pages']
theme: minima