title: Lords of the Pit
description: "The Lords of the Pit are the United States’ premiere Old School Magic: the Gathering club based out of Chicago, IL. Members of this group include current club members ('Lords') as well as prospective new members ('Thrulls')."
baseurl: /
url: https://lordsofthepit.com
s3BucketPrefix: https://lordsofthepit.s3.us-east-2.amazonaws.com
permalink: pretty
sort_by: year, month
markdown: kramdown
plugins:
  - jekyll-feed
include: ['_pages']
theme: minima
